name: Automatic release on tags

on:
  schedule:
    - cron: "0 17 * * 5"
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set tag
        uses: technote-space/package-version-check-action@v1
      - name: Get version
        run: echo "NEXT_VERSION=${HEAD_REF#release/}" >> $GITHUB_ENV
        env:
          HEAD_REF: ${{ github.head_ref }}