name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.JS
      uses: actions/setup-node@v2-beta
      with:
        node-version: '17'

    - name: Install NPM dependencies
      run: npm install

    - name: Build JS
      run: npm run build
      
    - name: Deploy Action
      uses: bumfo/action-deploy@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
